# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "01921774055436e2de550386dbc834a7"
name = "preorder-order-tagger"
handle = "preorder-order-tagger"
application_url = "https://18006602dcbe.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/app/orders-create"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_orders,write_orders,write_products"

[auth]
redirect_urls = ["https://18006602dcbe.ngrok-free.app/auth/callback", "https://18006602dcbe.ngrok-free.app/auth/shopify/callback", "https://18006602dcbe.ngrok-free.app/api/auth/callback"]

[pos]
embedded = false
